### ISSUE TITLE
Meta Tag

### ISSUE THREAD

**Issue by tegarimansyah** [pyconid/pyconid2019#12]
we need meta tag for display content while sharing on social media.

Ref

* https://www.w3schools.com/tags/tag_meta.asp
* https://css-tricks.com/essential-meta-tags-social-media/

**Comment by ridhof** [comment]
harusnya kalau error juga kayaknya ga ganggu konten ya mas, aku belum bisa bikin PR karena desktop ku penuh 

atau aku coba langsung code lewat github aja

**Comment by oonid** [comment]
issue ini kayaknya udah bisa ditutup ya mas @tegarimansyah mas @ridhof 
nanti kalo dibutuhkan bisa dibuka lagi :D
