### ISSUE TITLE
About, Speakers, Contact etc is not available

### ISSUE THREAD

**Issue by tegarimansyah** [pyconid/pyconid2019#2]
By default, pelican will use index.html for templating. If we want to use another template, we can use `Template: template_name` in our markdown content and make sure `template_name.html` is available in themes.

ref: https://docs.getpelican.com/en/latest/faq.html#how-do-i-assign-custom-templates-on-a-per-page-basis

**Comment by tegarimansyah** [comment]
sample of implementation:

https://github.com/pyconid/pyconid2019/blame/57d32aa1182f29ae5f7b3c39a0345c0deeeb6e81/content/pages/about.md#L2

**Comment by ridhof** [comment]
okey

**Comment by dwisulfahnur** [comment]
Hello,
I've made a PR for this issue, It should be able to solve this issue. #3 
Thanks

**Comment by tegarimansyah** [comment]
Nice! Thank you a lot @dwisulfahnur
