### ISSUE TITLE
add navigation to participant ticketing

### ISSUE THREAD

**Issue by ridhof** [pyconid/pyconid2019#24]
Participant's Ticketing will be open soon and the ticketing system is almost done!
Worry not, we are not going to develop ticketing system. Everything is handled by our partner. 
But still, we need inform website's visitor about the ticketing page. So here are the information you need to know:

- Ticketing system will be deployed on ticket.pycon.id (as I write this issue, it is still hasn't been deployed yet)

But we have to act faster, we need to inform visitor about ticketing system url by:
1. When user click 'Register as Participant' button at landing page ( here http://pycon.id/ ), direct them into the ticketing system url.
2. On participant's page ( here https://pycon.id/participant-mail-list ), inform the visitor about ticketing system and provide the url so visitor could directly visit the ticketing system.

Feel free to comment here if you are willing to help and please do a PR!

**Comment by dwisulfahnur** [comment]
Hello @ridhof ,

I have made a PR for the first point of this issue.
For the second point, will we delete the mailing list form?
