### ISSUE TITLE
Fix Time Format on Schedule Views

### ISSUE THREAD

**Issue by ridhof** [pyconid/pyconid2019#33]
we have views that display schedule of PyCon Indonesia, here https://pycon.id/schedule
therefore, the time format is a bit confusing because it's displaying AM/PM even tho it's 24-hour based.

to make it clear for our visitor, let use 24-hour based so we have to remove AM/PM part.
I hope someone could help us by make this as PR, thank you!

**Comment by oonid** [comment]
mas @ridhof 
PTAL my PR related to this issue.
https://github.com/pyconid/pyconid2019/pull/34

**Comment by ridhof** [comment]
thank you mas @oonid 
issue will be closed temporary because it has been solved current issue, but will reopened on another occasion if another issue appears.
