### ISSUE TITLE
[urgent] landing page content is still using template's content

### ISSUE THREAD

**Issue by ridhof** [pyconid/pyconid2019#5]
Landing page content is still using template's content.
Landing page content is a crucial information that must be provided first. It's the first page that most visitors will see first.

this issue is urgently needed before August 19th

What are the content that must be provided in landing page?
It could be the same as previous PyCon Indonesia landing page content. 
To make it easier we could make a dynamic templating where we could change such as:
- logo
- name
- date
- place
- ticket link
- submit paper link (to other page)
- venue sponsors
- diamond sponsors
- platinum sponsors
- silver sponsors
- ticketing partner
- partners
- our email to be contacted
- social media link

for references, we could use [previous year's landing page](https://pycon.id/)

in case pycon.id will be replaced with pycon 2019, I will provide the information provided by previous PyCon:

About:
PyCon Indonesia is a conference where Python users, or people interested in Python, gather to learn from each other and meet other members of the community. We hope that everyone joining PyCon ID will not only learn new and exciting things, but also meet new friends and strengthen the connection with the community, and thus the community itself. This year, we chose "Python for Everyone" as our theme. The Pycon ID staff is continuing to work hard on making a conference that will allow everyone to have a great time and unlock new possibilities through Python.

Call for Paper
PyCon Indonesia is pleased to announce that the Call For Proposals is now open. We are calling out for speakers to share their Python knowledge (in the form of Talks, Workshop and Posters) which would intrigue the Python community at this event! We’re looking for proposals on every aspect of Python: from basic to advanced levels. We’re interested to see all content that’s interesting and engaging to the Python community, whether it be tutorials, case studies, interactive sessions, or even how you and your organization works with Python. So if you have something that the community might be interested in, let us know; and don’t worry if you’re a seasoned engineer or a novice with no experience of presenting at a conference before; what matters is the content that you’ll be sharing with the community.

**Comment by tegarimansyah** [comment]
Mungkin aku bisa bantu untuk minggu ini di

- [x] logo
- [x] name
- [x] date
- [x] place

**Comment by ridhof** [comment]
> Mungkin aku bisa bantu untuk minggu ini di
> 
> * [ ]  logo
> * [ ]  name
> * [ ]  date
> * [ ]  place

actually there is still rest of list that aren't really in the top priority, here are the rest priority that should be done:
* [x]  about pycon indonesia
* [x]  about call for paper
* [x]  email to be contacted
* [x]  social media link

is anyone willingly to make a PR for those rest things?

**Comment by ridhof** [comment]
> > Mungkin aku bisa bantu untuk minggu ini di
> > 
> > * [ ]   logo
> > * [ ]   name
> > * [ ]   date
> > * [ ]   place
> 
> actually there is still rest of list that aren't really in the top priority, here are the rest priority that should be done:
> 
> * [ ]   about pycon indonesia
> * [ ]   about call for paper
> * [ ]   email to be contacted
> * [ ]   social media link
> 
> is anyone willingly to make a PR for those rest things?

I'll handle the rest

**Comment by tegarimansyah** [comment]
Karena mau rilis, mending beberapa page dihapus dulu atau langsung di ganti ke coming soon. Agar jelek soalnya kalo pake lorem ipsum gitu.

**Comment by ridhof** [comment]
done ya mas? mungkin bisa diclose issue dulu kalau udah done biar bisa fokus ke issue yang lain @tegarimansyah
