### ISSUE TITLE
page and its content for CFP (call for paper) is needed

### ISSUE THREAD

**Issue by ridhof** [pyconid/pyconid2019#6]
every conferences will open for CFP (Call for Paper), and it's including the next PyCon ID. previous year, we have a page that called [Speak at Pycon ID](https://pycon.id/call-for-paper/), to make it easier let use the same url. and let use the same content from the previous year as the initial content (we could change it later).

content needed for call for paper page are:
- speak at PyCon ID
- proposal types
- guidelines for proposal submission
- link to papercall (for temporal link we could use this one https://www.papercall.io/pyconid2018)

and content for each points in case the previous year PyCon ID page is overwritten by PyCon
ID 2019 we could use these contents:

**Speak at Pycon ID**
PyCon Indonesia is pleased to announce that the Call For Proposals is now open. We are calling out for speakers to share their Python knowledge which would intrigue the Python community at this event!

We’re looking for proposals on every aspect of Python: from basic to advanced levels. We’re interested to see all content that’s interesting and engaging to the Python community, whether it be tutorials, case studies, interactive sessions, or even how you and your organization works with Python. So if you have something that the community might be interested in, let us know; and don’t worry if you’re a seasoned engineer or a novice with no experience of presenting at a conference before; what matters is the content that you’ll be sharing with the community.

**Proposal Types**
Talks are limited to a maximum of 35 minutes, and may preferably be accompanied with helping material (presentation, document, etc). Talks could be on a variety of topics (for further details and inspiration, check out the next section).

Workshops, tutorials, and interactive sessions have a 60 minutes limit. For workshops, we encourage tutorials that can be helpful to the community at any level, whether beginner or advanced. Both time slots include time for questions from the audience, so please plan your talk accordingly.

**Guidelines for Proposal Submission**
While there’s not a strict criteria on the proposal content, there are a few guidelines to be followed while submitting a proposal and you must follow the Code of Conduct.

The proposal should be concise and relevant to the event. Please be sure to mention necessary versions and environment setup configurations, where applicable.

It’s preferable if your associated organization’s name/branding is mentioned only at the beginning of the proposal, and the rest of the content is unbiased and generic. Moreover, any platform, technology, browser, and OS biases should also be avoided. Selection status of proposals will be notified via email.

Feel free to submit multiple proposals. For any questions, please write to conf@python.or.id Last, but not the least, we accept talks in Bahasa Indonesia and English. After all, it’s PyCon Indonesia!

**Comment by dwisulfahnur** [comment]
I've added a new page on my latest PR (#10)
Please review especially about the **concern** section on my PR Description.
Thanks.

**Comment by ridhof** [comment]
> I've added a new page on my latest PR (#10)
> Please review especially about the **concern** section on my PR Description.
> Thanks.

karena untuk saat ini yang menjadi prioritas masih landing page setelah itu sponsor, jadi untuk yang CFP mungkin review dan feedbacknya agak delay ya mas. Karena untuk landing page perlu segera rilis bersamaan dengan poster kurang lebih hari ini/besok. Dan untuk sponsor perlu tidak selama setelah landing page rilis. Mungkin mas Dwi punya kenalan yang mau contrib juga untuk yang halaman Sponsor?

**Comment by dwisulfahnur** [comment]
Siap mas @ridhof , kayaknya udah di merge sama mas Tegar.
Untuk halaman Sponsor belum yah? Tema yang di halaman ini kayaknya bisa diterapin di halaman sponsor.
